name: 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download Branch
      uses: actions/checkout@v2

    - name: Update Submodule
      run: |
        git submodule init
        git submodule update --remote
    - name: Prepare Node Env
      uses: actions/setup-node@v1
      with:
        node-version: "10.x"

    - name: Hexo Generate
      run: |
        rm -f .yarnclean
        yarn --frozen-lockfile --ignore-engines --ignore-optional --non-interactive --silent --ignore-scripts --production=false
        rm -rf ./public
        yarn run hexo clean
        yarn run hexo generate

    - name: Deploy static to Tencent CloudBase
        uses: TencentCloudBase/cloudbase-action@v1.1.0
        with:
          secretId: ${{ secrets.SECRET_ID }}
          secretKey: ${{ secrets.SECRET_KEY }}
          envId: ${{ secrets.ENV_ID }}
          staticSrcPath: ./public/